
vich_uploader:
    db_driver: orm
    mappings:
        thumbnails:
            uri_prefix: '%app.path.tools_thumbnails%'
            upload_destination: '%kernel.project_dir%/public%app.path.tools_thumbnails%'